/* stubgen: extract per-opcode stubs from translated units (test tooling).
 *
 *   stubgen OUT.s UNIT.s...
 *
 * For each distinct opcode form -- mnemonic, plus "/m" when an operand is a
 * memory-resident MIPS register ($s0 $s1 $s2 $k0 $k1 $gp $fp $ra) -- takes
 * the first translated group (text from `L_<ADDR>:` to the next label or
 * the footer) and emits it as a stand-alone stub `_m2m_stub_<n>` that ends
 * with a jump to `_m2m_exit`. Control transfers, eret, syscall/break and
 * groups that leave the unit are skipped (they are covered by lockstep).
 * Also emits `_m2m_stub_table` = {stub, pc, word} rows and
 * `_m2m_stub_count`. The text is copied, never interpreted. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

enum { MAX_FORMS = 1024 };

static const char *const skip_mnemonics[] = {
    "j",     "jal",   "jr",     "jalr",   "beq",     "bne",     "blez",
    "bgtz",  "beql",  "bnel",   "blezl",  "bgtzl",   "bltz",    "bgez",
    "bltzl", "bgezl", "bltzal", "bgezal", "bltzall", "bgezall", "bc1f",
    "bc1t",  "bc1fl", "bc1tl",  "eret",   "syscall", "break",   NULL};

static const char *const mem_regs[] = {"$s0", "$s1", "$s2", "$k0", "$k1",
                                       "$gp", "$fp", "$ra", NULL};

static char forms[MAX_FORMS][40];
static unsigned nforms;

static char *slurp(const char *path) {
  FILE *f = fopen(path, "rb");
  if (!f)
    return NULL;
  fseek(f, 0, SEEK_END);
  long n = ftell(f);
  rewind(f);
  char *buf = malloc((size_t)n + 1);
  buf[fread(buf, 1, (size_t)n, f)] = '\0';
  fclose(f);
  return buf;
}

/* Whether [g, q) contains `s`. */
static int contains(const char *g, const char *q, const char *s) {
  const char *h = strstr(g, s);
  return h && h < q;
}

static int is_label_line(const char *p, char addr[9]) {
  while (*p == ' ' || *p == '\t')
    p++;
  if (strncmp(p, "L_", 2) != 0)
    return 0;
  for (int i = 0; i < 8; i++) {
    char c = p[2 + i];
    if (!((c >= '0' && c <= '9') || (c >= 'A' && c <= 'F')))
      return 0;
    addr[i] = c;
  }
  addr[8] = '\0';
  return p[10] == ':';
}

/* Writes `line` with every unit-local label L<x>_<ADDR> renamed. */
static void emit_line(FILE *out, const char *line, size_t len, unsigned n) {
  for (size_t i = 0; i < len;) {
    if (line[i] == 'L' &&
        (i == 0 ||
         !(line[i - 1] == '_' || (line[i - 1] >= 'A' && line[i - 1] <= 'Z') ||
           (line[i - 1] >= 'a' && line[i - 1] <= 'z') ||
           (line[i - 1] >= '0' && line[i - 1] <= '9')))) {
      size_t j = i + 1;
      while (j < len && ((line[j] >= 'a' && line[j] <= 'z') ||
                         (line[j] >= 'A' && line[j] <= 'Z') ||
                         (line[j] >= '0' && line[j] <= '9') || line[j] == '_'))
        j++;
      if (memchr(line + i, '_', j - i) && j - i >= 10) {
        fprintf(out, "LS%u%.*s", n, (int)(j - i), line + i);
        i = j;
        continue;
      }
    }
    if (line[i] == '/' && i + 1 < len && line[i + 1] == '/') {
      fprintf(out, "%.*s", (int)(len - i), line + i); /* comments as-is */
      return;
    }
    fputc(line[i++], out);
  }
}

int main(int argc, char **argv) {
  if (argc < 2) {
    fprintf(stderr, "usage: %s OUT.s UNIT.s...\n", argv[0]);
    return 2;
  }
  FILE *out = fopen(argv[1], "w");
  if (!out) {
    perror(argv[1]);
    return 1;
  }
  fprintf(out, "// Generated by stubgen: per-opcode stubs (test only).\n"
               ".include \"src/native/m2m.inc\"\n.text\n.p2align 2\n");
  unsigned n = 0;
  unsigned pcs[MAX_FORMS], words[MAX_FORMS];
  for (int a = 2; a < argc; a++) {
    char *text = slurp(argv[a]);
    if (!text)
      continue;
    char *end = strstr(text, ".section __TEXT,__const");
    if (end)
      *end = '\0';
    for (char *p = text; p && *p;) {
      char addr[9];
      char *eol = strchr(p, '\n');
      if (!is_label_line(p, addr)) {
        p = eol ? eol + 1 : NULL;
        continue;
      }
      /* Group: from this label to the next L_ label line. */
      char *g = p, *q = eol ? eol + 1 : p + strlen(p);
      for (;;) {
        char tmp[9];
        if (!*q || is_label_line(q, tmp))
          break;
        char *e2 = strchr(q, '\n');
        q = e2 ? e2 + 1 : q + strlen(q);
      }
      /* Provenance comment: "// ADDR: WORD mnemonic operands". */
      char *c = strstr(g, "//");
      char mnem[24] = "", word[9] = "";
      if (c && c < q)
        sscanf(c, "// %*8s %8s %23s", word, mnem);
      int skip =
          !mnem[0] || contains(g, q, "M2M_GOTO") || contains(g, q, "M2M_FALL");
      for (int k = 0; skip_mnemonics[k]; k++)
        if (!strcmp(mnem, skip_mnemonics[k]))
          skip = 1;
      char key[40];
      int memreg = 0;
      char *cl = c ? strchr(c, '\n') : NULL;
      for (int k = 0; mem_regs[k] && c; k++) {
        char *h = strstr(c, mem_regs[k]);
        if (h && (!cl || h < cl))
          memreg = 1;
      }
      snprintf(key, sizeof(key), "%s%s", mnem, memreg ? "/m" : "");
      for (unsigned k = 0; k < nforms && !skip; k++)
        if (!strcmp(forms[k], key))
          skip = 1;
      if (!skip && nforms < MAX_FORMS) {
        strcpy(forms[nforms++], key);
        fprintf(out, "\n// form %s\n.globl _m2m_stub_%u\n_m2m_stub_%u:\n", key,
                n, n);
        for (char *l = g; l < q;) {
          char *e3 = memchr(l, '\n', (size_t)(q - l));
          size_t len = e3 ? (size_t)(e3 - l) : (size_t)(q - l);
          emit_line(out, l, len, n);
          fputc('\n', out);
          l += len + 1;
        }
        fprintf(out, "    b     _m2m_exit\n");
        pcs[n] = (unsigned)strtoul(addr, NULL, 16);
        words[n] = (unsigned)strtoul(word, NULL, 16);
        n++;
      }
      p = q;
    }
    free(text);
  }
  fprintf(out, "\n.section __DATA,__const\n.p2align 3\n.globl _m2m_stub_table\n"
               "_m2m_stub_table:\n");
  for (unsigned i = 0; i < n; i++)
    fprintf(out, "    .quad _m2m_stub_%u\n    .long 0x%08X, 0x%08X\n", i,
            pcs[i], words[i]);
  fprintf(out,
          "    .quad 0\n    .long 0, 0\n.globl _m2m_stub_count\n"
          "_m2m_stub_count:\n    .long %u\n",
          n);
  for (unsigned i = 0; i < nforms; i++)
    fprintf(out, "// covered: %s\n", forms[i]);
  fclose(out);
  return 0;
}
